# Generated by Django 3.0.6 on 2021-02-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210222_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='class_in_school',
            field=models.TextField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(default='attack helicopter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_in_school',
            field=models.IntegerField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(default='null', max_length=100),
        ),
    ]
