# Generated by Django 3.0.6 on 2021-02-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210222_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(default='attack helicopter', max_length=6),
        ),
    ]
