# Generated by Django 3.0.6 on 2021-02-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210222_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year_in_school',
            field=models.IntegerField(default='1', verbose_name=range(1, 50)),
        ),
    ]
