# Generated by Django 3.0.6 on 2021-02-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210222_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year_in_school',
            field=models.IntegerField(default='1', verbose_name=range(8, 12)),
        ),
    ]
