# Generated by Django 3.0.6 on 2021-02-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210222_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(default='null', max_length=512),
        ),
    ]
