# Generated by Django 3.0.6 on 2021-02-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='semester',
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=20),
        ),
    ]
