# Generated by Django 3.0.6 on 2021-02-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210222_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_in_school',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=20),
        ),
    ]
