# Generated by Django 3.0.6 on 2021-02-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210222_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(choices=[('NY', 'NY'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='0', max_length=20),
        ),
    ]
